name: flutter_tab_indicator
description: Flutter - Projeto Tab Indicator;

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  circular_bottom_navigation: ^1.0.1
  dio: ^2.1.16
  rxdart: ^0.22.2
  bloc_pattern: ^2.3.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true